name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF reports

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read # required for private repos using upload-sarif
      security-events: write
    name: Run Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semgrep (if not installed)
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif
        continue-on-error: true  # Allow workflow to continue even if Semgrep fails

      - name: Debug SARIF Output
        run: ls -lah && cat semgrep.sarif
        if: always()

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
