name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF reports

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read # required for private repos using upload-sarif
    name: Run Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: 'auto' # Replace with your ruleset
          generateSarif: true
          auditOn: 'push,pull_request'
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        continue-on-error: true  # Prevent CI from failing if issues are found

      - name: Debug SARIF Output
        run: cat report.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
        if: always()

      - name: Save Semgrep Logs
        run: cat report.sarif > semgrep.log

      - name: Upload Semgrep Log
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-log
          path: semgrep.log
