name: Vorpal Security Scan with CodeQL SARIF

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  vorpal_analysis:
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read # required for private repos using upload-sarif
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Collect all source files
        id: source-files
        run: |
          FILES=$(find . -type f \( -name "*.cs" -o -name "*.java" -o -name "*.js" -o -name "*.py" \) | tr '\n' ',')
          echo "source_files=$FILES" >> $GITHUB_ENV

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: result.errorformat
