name: Checkmarx Vorpal Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

permissions:
  security-events: write  # Required for uploading SARIF results

jobs:
  security_scan:
    name: Run Vorpal Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Vorpal Security Scan
        run: |
          docker run --rm \
            checkmarx/vorpal-cli:1.0.116 \
            -s . -r /app/vorpal-results.sarif

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vorpal-results.sarif
