name: Checkmarx Vorpal Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF results

jobs:
  security_scan:
    name: Run Vorpal Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Repository Files
        run: ls -R

      - name: Find and Copy Files into a Temporary Directory
        run: |
          mkdir -p vorpal_scan
          find . -type f \( -name "*.cs" -o -name "*.java" -o -name "*.js" -o -name "*.py" \) -exec cp --parents {} vorpal_scan/ \;
          ls -R vorpal_scan  # Debug to ensure files are copied

      - name: Run Vorpal Security Scan for Each File
        run: |
          FILES=$(find vorpal_scan -type f \( -name "*.cs" -o -name "*.java" -o -name "*.js" -o -name "*.py" \))
          
          if [ -z "$FILES" ]; then
            echo "No supported source files found. Exiting."
            exit 0
          fi

          for FILE in $FILES; do
            echo "Scanning: $FILE"
            docker run --rm \
              -v $(pwd)/vorpal_scan:/app/vorpal_scan \
              checkmarx/vorpal-cli:1.0.116 \
              -s /app/$FILE -r /app/vorpal_scan/vorpal-results.sarif || true
          done

      - name: Move SARIF Results to Root Directory
        run: mv vorpal_scan/vorpal-results.sarif .

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vorpal-results.sarif
