name: Checkmarx Vorpal Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF results

jobs:
  security_scan:
    name: Run Vorpal Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find Files and Run Vorpal Security Scan
        run: |
          mkdir -p vorpal_scan results
          FILES=$(find . -type f \( -name "*.cs" -o -name "*.java" -o -name "*.js" -o -name "*.py" \))

          if [ -z "$FILES" ]; then
            echo "No supported source files found. Exiting."
            exit 0
          fi

          COUNT=1
          for FILE in $FILES; do
            echo "Scanning: $FILE"

            # Remove leading './' to get the correct path inside the container
            FILE_CLEANED=$(echo "$FILE" | sed 's|^\./||')

            docker run --rm \
              -v $(pwd)/vorpal_scan:/vorpal_scan \
              checkmarx/vorpal-cli:1.0.116 \
              -s "/vorpal_scan/$FILE_CLEANED" -r "/vorpal_scan/vorpal-results-$COUNT.sarif" || true

            COUNT=$((COUNT+1))
          done

      - name: Merge SARIF Files
        run: |
          echo '{"version": "2.1.0", "runs": []}' > merged-results.sarif
          for FILE in vorpal_scan/vorpal-results-*.sarif; do
            jq '.runs |= . + input.runs' merged-results.sarif "$FILE" > temp.sarif && mv temp.sarif merged-results.sarif
          done

      - name: Show Merged SARIF Results (Debug)
        run: cat merged-results.sarif

      - name: Upload Merged SARIF Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: merged-results.sarif
